name: 'dbt_hevo_zendesk'
version: '0.0.3'

config-version: 2

profile: 'default'

analysis-paths: ["analysis"]
asset-paths: ["assets"]
seed-paths: ["data"]
log-path: "logs"
macro-paths: ["macros"]
model-paths: ["models"]
packages-install-path: "modules"
snapshot-paths: ["snapshots"]
target-path: "target"
test-paths: ["tests"]

clean-targets:
  - "logs"
  - "modules"
  - "target"

query-comment: null

require-dbt-version: [">=1.5.0", "<2.0.0"]

quoting:
  database: false
  schema: false
  identifier: false

models:
  dbt_hevo_zendesk:
    staging:
      +schema: zendesk
      +enabled: true
      +quote_columns: true
      +materialized: view
